spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/Vet
    username: root
    password: Test@123
  jpa:
    hibernate:
      show-sql: true
server:
  error:
    include-stacktrace: never