USE Vet;

CREATE TABLE FUNCIONARIO
(
    ID_FUNCIONARIO INT PRIMARY KEY,
    NOME           VARCHAR(255),
    IDADE          INT,
    CPF_CNPJ       VARCHAR(14) UNIQUE,
    EMAIL          VARCHAR(100),
    SENHA          VARCHAR(50)
);

CREATE TABLE ATENDENTE
(
    ID_ATENDENTE   INT PRIMARY KEY,
    ID_FUNCIONARIO INT UNIQUE,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE TABLE VETERINARIO
(
    ID_VETERINARIO INT PRIMARY KEY,
    ID_FUNCIONARIO INT UNIQUE,
    CRMV           VARCHAR(20),
    ESPECIALIDADE  VARCHAR(100),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE TABLE TOSADOR
(
    ID_TOSADOR     INT PRIMARY KEY,
    ID_FUNCIONARIO INT UNIQUE,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);


CREATE TABLE USUARIO
(
    ID_USUARIO       INT PRIMARY KEY,
    NOME_USUARIO     VARCHAR(255),
    TELEFONE_USUARIO VARCHAR(20),
    EMAIL            VARCHAR(100),
    SENHA            VARCHAR(50)
);

CREATE TABLE ENDERECO
(
    ID_ENDERECO INT PRIMARY KEY,
    CEP         VARCHAR(10),
    RUA         VARCHAR(255),
    NUMERO      INT,
    BAIRRO      VARCHAR(100),
    CIDADE      VARCHAR(100),
    ESTADO      VARCHAR(50),
    PAIS        VARCHAR(50),
    COMPLEMENTO VARCHAR(255)
);

CREATE TABLE USUARIO_ENDERECO
(
    ID_USUARIO  INT,
    ID_ENDERECO INT,
    PRIMARY KEY (ID_USUARIO, ID_ENDERECO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO)
);

CREATE TABLE ANIMAL
(
    ID_ANIMAL            INT PRIMARY KEY,
    NOME_ANIMAL          VARCHAR(255),
    RACA                 VARCHAR(100),
    ALERGIA              VARCHAR(255),
    DATA_NASCIMENTO      DATE,
    STATUS_DO_TRATAMENTO VARCHAR(50)
);

CREATE TABLE DOENCA
(
    ID_DOENCA        INT PRIMARY KEY,
    NIVEL_PERIGO     VARCHAR(50),
    DESCRICAO_DOENCA VARCHAR(255)
);

CREATE TABLE ANIMAL_DOENCA
(
    ID_ANIMAL INT,
    ID_DOENCA INT,
    PRIMARY KEY (ID_ANIMAL, ID_DOENCA),
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL),
    FOREIGN KEY (ID_DOENCA) REFERENCES DOENCA (ID_DOENCA)
);

CREATE TABLE VACINA
(
    ID_VACINA         INT PRIMARY KEY,
    NOME_DA_VACINA    VARCHAR(255),
    DATA_DA_APLICACAO DATE
);

CREATE TABLE ANIMAL_VACINA
(
    ID_ANIMAL INT,
    ID_VACINA INT,
    PRIMARY KEY (ID_ANIMAL, ID_VACINA),
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL),
    FOREIGN KEY (ID_VACINA) REFERENCES VACINA (ID_VACINA)
);

CREATE TABLE PESO
(
    ID_PESO INT PRIMARY KEY,
    PESO    DECIMAL(5, 2),
    DATA    DATE
);

CREATE TABLE ANIMAL_PESO
(
    ID_ANIMAL INT,
    ID_PESO   INT,
    PRIMARY KEY (ID_ANIMAL, ID_PESO),
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL),
    FOREIGN KEY (ID_PESO) REFERENCES PESO (ID_PESO)
);

CREATE TABLE USUARIO_ANIMAL
(
    ID_USUARIO INT,
    ID_ANIMAL  INT,
    PRIMARY KEY (ID_USUARIO, ID_ANIMAL),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL)
);
